"""Self-play & adversarial defence — the headline page.

Shows the Stackelberg co-evolution dynamics, the multi-seed Modena
results, the Attacker-MoE emergent attack vocabulary, and the
held-out generalisation test. Designed to read top-to-bottom as a
narrative: framework -> training dynamics -> evaluation -> novelty.
"""

import sys
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
import streamlit as st

DASHBOARD = Path(__file__).parent.parent
sys.path.insert(0, str(DASHBOARD))

from utils.theme import (
    GLOBAL_CSS, BLUE, GREEN, ORANGE, RED, PURPLE, CYAN, GRAY,
    plotly_layout,
)
from utils.data_loader import (
    load_selfplay_history, load_selfplay_summary, load_selfplay_args,
    SELFPLAY_RUNS,
)

st.set_page_config(page_title="Self-Play", layout="wide",
                   initial_sidebar_state="expanded")
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)

st.title("Self-Play & Adversarial Defence")
st.caption(
    "An Attacker GNN and a Defender GNN co-evolve in a Stackelberg game. "
    "The defender learns to flag attacks generated by an opponent that "
    "is itself learning — and generalises to attacks never seen in training."
)

# Story map — quick orientation for a page that scrolls through many panels.
st.markdown(
    """
    <div style="display:flex; gap:8px; flex-wrap:wrap; margin:6px 0 14px;">
        <span style="background:rgba(74,222,128,0.14); color:#4ade80;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">1 · Headline</span>
        <span style="background:rgba(96,165,250,0.14); color:#60a5fa;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">2 · Training dynamics</span>
        <span style="background:rgba(167,139,250,0.14); color:#a78bfa;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">3 · Reproducibility</span>
        <span style="background:rgba(251,146,60,0.14); color:#fb923c;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">4 · Held-out generalisation</span>
        <span style="background:rgba(34,211,238,0.14); color:#22d3ee;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">5 · Emergent vocabulary</span>
        <span style="background:rgba(248,113,113,0.14); color:#f87171;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">6 · Classical baselines</span>
        <span style="background:rgba(155,155,155,0.14); color:#9ca3af;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">7 · Robustness curve</span>
        <span style="background:rgba(74,222,128,0.14); color:#4ade80;
                     padding:4px 10px; border-radius:10px; font-size:0.75rem;
                     font-weight:600;">8 · Cross-network transfer</span>
    </div>
    """,
    unsafe_allow_html=True,
)

summary = load_selfplay_summary()


# ── Headline numbers ──────────────────────────────────────────────────
st.markdown("### Headline — Modena, 30 epochs, attacker MoE")

if summary.get("atkmoe"):
    pre = summary["atkmoe"]["pretrained"]
    sp = summary["atkmoe"]["sp_moe"]
    c1, c2, c3, c4 = st.columns(4)

    def _delta(new, old, fmt="{:+.3f}"):
        d = new - old
        return fmt.format(d), "normal" if abs(d) < 1e-3 else (
            "off" if d < 0 else "normal")

    c1.metric("Anomaly F1",
              f"{sp['f1']:.3f}",
              f"{sp['f1'] - pre['f1']:+.3f} vs pretrained")
    c2.metric("Pressure MAE (m)",
              f"{sp['p_mae']:.3f}",
              f"{sp['p_mae'] - pre['p_mae']:+.3f} (lower is better)",
              delta_color="inverse")
    c3.metric("Targeted F1",
              f"{sp['per_attack']['targeted']['f1']:.3f}",
              f"{sp['per_attack']['targeted']['f1'] - pre['per_attack']['targeted']['f1']:+.3f}")
    c4.metric("Stealthy F1",
              f"{sp['per_attack']['stealthy']['f1']:.3f}",
              f"{sp['per_attack']['stealthy']['f1'] - pre['per_attack']['stealthy']['f1']:+.3f}")
else:
    st.warning("Self-play eval JSON not found — run `scripts/eval_atkmoe.py`.")

st.divider()

# ── Co-evolution training dynamics ────────────────────────────────────
st.markdown("### Training dynamics")
st.caption(
    "Adversarial F1 (defender vs current attacker) and hand-crafted F1 "
    "(defender vs the original 5-class corruption set) tracked across "
    "epochs. Vertical lines mark auto-curriculum events where the "
    "stealth budget grew because the defender was beating the attacker."
)

variant = st.radio(
    "Run", ["scratch", "single", "attacker_moe"],
    format_func={
        "scratch": "Scratch (no pretrained defender)",
        "single": "Pretrained + single attacker fine-tune",
        "attacker_moe": "Pretrained + Attacker-MoE fine-tune",
    }.get,
    horizontal=True,
)

hist = load_selfplay_history("Modena", variant)
args = load_selfplay_args("Modena", variant)

if hist:
    epochs = [e["epoch"] for e in hist]
    hand = [e.get("hand_f1", 0) for e in hist]
    adv = [e.get("adv_f1", 0) for e in hist]
    dmg = [e.get("atk_damage", 0) for e in hist]
    recon = [e.get("def_recon", 0) for e in hist]
    ks = [e.get("k_p", None) for e in hist]

    col_a, col_b = st.columns(2)
    with col_a:
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=epochs, y=hand, mode="lines",
            name="Hand-crafted F1", line=dict(color=BLUE, width=2.5),
        ))
        fig.add_trace(go.Scatter(
            x=epochs, y=adv, mode="lines",
            name="Adversarial F1", line=dict(color=PURPLE, width=2.5),
        ))
        # Curriculum vlines
        last_k = ks[0] if ks and ks[0] is not None else None
        for i, k in enumerate(ks or []):
            if k is not None and last_k is not None and k > last_k:
                fig.add_vline(
                    x=epochs[i], line_dash="dot",
                    line_color=GREEN, opacity=0.5,
                    annotation_text=f"k→{k}",
                    annotation_position="top",
                    annotation_font_size=9,
                )
                last_k = k
        fig.update_layout(**plotly_layout(
            title="Defender F1 — co-evolution",
            xaxis_title="Epoch", yaxis_title="F1",
            yaxis=dict(range=[0.4, 1.0]),
            height=320, showlegend=True,
        ))
        st.plotly_chart(fig, width="stretch")

    with col_b:
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=epochs, y=dmg, mode="lines",
            name="Attacker damage (MSE)", line=dict(color=RED, width=2),
            yaxis="y",
        ))
        fig.add_trace(go.Scatter(
            x=epochs, y=recon, mode="lines",
            name="Defender recon loss", line=dict(color=GREEN, width=2),
            yaxis="y2",
        ))
        layout = plotly_layout(
            title="Adversarial dynamics",
            xaxis_title="Epoch",
            yaxis=dict(title=dict(text="Attacker damage",
                                  font=dict(color=RED)),
                       tickfont=dict(color=RED)),
            yaxis2=dict(title=dict(text="Defender recon",
                                   font=dict(color=GREEN)),
                        tickfont=dict(color=GREEN), overlaying="y",
                        side="right", showgrid=False),
            height=320, showlegend=True,
        )
        fig.update_layout(**layout)
        st.plotly_chart(fig, width="stretch")

    if args:
        with st.expander("Run hyper-parameters"):
            cols = st.columns(4)
            for i, (k, v) in enumerate(args.items()):
                cols[i % 4].markdown(f"**{k}**  \n`{v}`")
else:
    st.info(f"History for variant `{variant}` not available.")

st.divider()

# ── Multi-seed reproducibility ────────────────────────────────────────
st.markdown("### Reproducibility — three seeds on Modena")
st.caption(
    "Each bar is the mean over three independent training runs; "
    "error bars are ± one standard deviation."
)

if summary.get("multiseed"):
    pre = summary["multiseed"]["pretrained"]
    sps = summary["multiseed"]["selfplay_seeds"]
    attacks = ["random", "replay", "stealthy", "noise", "targeted"]
    pre_f1 = [pre["per_attack"].get(a, {}).get("f1", 0) for a in attacks]
    sp_f1 = np.array([
        [sp["per_attack"].get(a, {}).get("f1", 0) for a in attacks]
        for sp in sps
    ])
    sp_mean = sp_f1.mean(axis=0)
    sp_std = sp_f1.std(axis=0, ddof=1) if sp_f1.shape[0] > 1 else np.zeros(len(attacks))

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=attacks, y=pre_f1, name="Pretrained",
        marker_color=BLUE, opacity=0.55,
        text=[f"{v:.2f}" for v in pre_f1], textposition="outside",
    ))
    fig.add_trace(go.Bar(
        x=attacks, y=sp_mean, name="Self-play (3 seeds)",
        marker_color=GREEN, opacity=0.92,
        error_y=dict(type="data", array=sp_std, color=GRAY, thickness=1.5),
        text=[f"{v:.2f}" for v in sp_mean], textposition="outside",
    ))
    fig.update_layout(**plotly_layout(
        title="Per-attack F1 with error bars",
        yaxis=dict(range=[0, 1.15], title="F1"),
        barmode="group", height=360, showlegend=True,
    ))
    st.plotly_chart(fig, width="stretch")

    cols = st.columns(3)
    cols[0].metric(
        "Pressure MAE",
        f"{np.mean([sp['p_mae'] for sp in sps]):.3f} ± {np.std([sp['p_mae'] for sp in sps], ddof=1):.3f}",
        f"{np.mean([sp['p_mae'] for sp in sps]) - pre['p_mae']:+.3f} m",
        delta_color="inverse",
    )
    cols[1].metric(
        "Overall AUROC",
        f"{np.mean([sp['auroc'] for sp in sps]):.3f}",
    )
    cols[2].metric(
        "Targeted F1",
        f"{sp_mean[attacks.index('targeted')]:.3f} ± "
        f"{sp_std[attacks.index('targeted')]:.3f}",
    )
else:
    st.info("Run `scripts/eval_multiseed.py` to populate this section.")

st.divider()

# ── Held-out novel attack generalisation ──────────────────────────────
st.markdown("### Generalisation — novel attacks not in training")
st.caption(
    "The defenders were trained on the original five hand-crafted attacks; "
    "the two attacks below were synthesised separately and held out. "
    "Sinusoidal injection adds A·sin(ωt+φ); sensor swap exchanges the "
    "pressure observation of two attacked sensors."
)

if summary.get("heldout"):
    cols = st.columns(2)
    defs = ["pretrained", "sp_single", "sp_moe"]
    labels = ["Pretrained", "SP single", "SP MoE"]
    palette = [BLUE, PURPLE, GREEN]

    for col, kind in zip(cols, summary["heldout"].keys()):
        d = summary["heldout"][kind]
        f1 = [d[k]["f1"] for k in defs]
        au = [d[k]["auroc"] for k in defs]
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=labels, y=f1, name="F1", marker_color=BLUE, opacity=0.7,
            text=[f"{v:.3f}" for v in f1], textposition="outside",
        ))
        fig.add_trace(go.Bar(
            x=labels, y=au, name="AUROC", marker_color=PURPLE, opacity=0.92,
            text=[f"{v:.3f}" for v in au], textposition="outside",
        ))
        fig.update_layout(**plotly_layout(
            title=f"Novel attack: {kind}",
            yaxis=dict(range=[0.6, 1.0], title="Score"),
            barmode="group", height=320, showlegend=True,
        ))
        col.plotly_chart(fig, width="stretch")

    st.success(
        "Self-play Attacker-MoE wins on **both** novel attacks despite "
        "neither attack being in its training distribution — evidence "
        "that the framework yields genuine adversarial robustness."
    )
else:
    st.info("Run `scripts/heldout_novel_attack.py` to populate this section.")

st.divider()

# ── Emergent attack vocabulary ────────────────────────────────────────
st.markdown("### Emergent attack vocabulary")
st.caption(
    "The Attacker-MoE was trained without attack-class supervision. "
    "Yet the router auto-partitioned its 4 experts into **two functional "
    "families** — bold (random / targeted / noise) vs subtle "
    "(replay / stealthy)."
)

vocab_path = DASHBOARD.parent / "presentation" / "charts" / "vocab_attackmoe.png"
if vocab_path.exists():
    st.image(str(vocab_path), caption="t-SNE projection — left coloured by "
                                      "ground-truth class, right by router pick.",
             width="stretch")
else:
    st.info("Run `scripts/vocabulary_mining.py` to generate the projection.")


col1, col2 = st.columns(2)
with col1:
    st.markdown("**Expert 2 — bold attacks** (87 picks)")
    st.markdown(
        "- 30% random  \n"
        "- 21% targeted  \n"
        "- 18% noise  \n"
        "- 15% stealthy  \n"
        "- 13% replay"
    )
with col2:
    st.markdown("**Expert 3 — subtle attacks** (61 picks)")
    st.markdown(
        "- 33% replay  \n"
        "- 31% stealthy  \n"
        "- 16% targeted  \n"
        "- 13% noise  \n"
        "-  7% random"
    )

st.divider()

# ── Classical baselines ───────────────────────────────────────────────
st.markdown("### Classical baselines — what does the GNN actually buy us?")
st.caption(
    "Three closed-form estimators (mean imputation, pseudo-inverse, "
    "Laplacian-regularised WLS) run on the same test split. The GNN "
    "MoE wins by an order of magnitude on reconstruction and 4-5× on "
    "anomaly F1."
)
cls_path = DASHBOARD.parent / "presentation" / "charts" / "classical_baselines.png"
if cls_path.exists():
    st.image(str(cls_path), width="stretch")
else:
    st.info("Run `scripts/eval_classical_baselines.py`.")

st.divider()

# ── Adversarial robustness curve ─────────────────────────────────────
st.markdown("### Adversarial robustness — defenders under varying attack budget")
st.caption(
    "For each stealth budget ε we re-evaluate the three defenders "
    "against the (same) trained attacker. The self-play MoE stays "
    "ahead of the supervised baseline at every budget."
)
rob_path = DASHBOARD.parent / "presentation" / "charts" / "selfplay_robustness.png"
if rob_path.exists():
    st.image(str(rob_path), width="stretch")
else:
    st.info("Run `scripts/eval_robustness.py`.")

st.divider()

# ── Cross-network transfer ───────────────────────────────────────────
st.markdown("### Cross-network transfer — attacker trained on Modena")
st.caption(
    "We freeze the Modena-trained attacker and turn it loose on each "
    "network's defenders. Self-play wins on Net3 and ties on Modena; "
    "Net1's small graph is the same regression we saw earlier."
)
cn_path = DASHBOARD.parent / "presentation" / "charts" / "selfplay_crossnet.png"
if cn_path.exists():
    st.image(str(cn_path), width="stretch")
else:
    st.info("Run `scripts/eval_crossnet.py`.")

st.divider()
st.markdown(
    """
    ### Honest limitations
    - **Replay** (single-copy attack) is informationally close to clean
      data; absolute F1 is still in the 0.16–0.23 range. Information-theoretic ceiling.
    - **Net1** regresses under self-play — the 11-node graph already
      saturates the pretrained capacity, so adversarial fine-tuning hurts more than it helps.
    - **Mode collapse** in the Attacker-MoE: 2 of 4 experts are unused.
      The two-family discovery is real, but pushing diversity loss
      harder is open work.
    """
)
